package ec.gob.mag.ws;

import org.modelmapper.ModelMapper;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;
import org.springframework.ws.server.endpoint.annotation.Endpoint;
import org.springframework.ws.server.endpoint.annotation.PayloadRoot;
import org.springframework.ws.server.endpoint.annotation.ResponsePayload;

import ec.gob.mag.interoperabilidad.proamazonia.dto.CabeceraGuiaPrimariaDto;
import ec.gob.mag.interoperabilidad.proamazonia.dto.DestinoClienteFinalGpDto;
import ec.gob.mag.interoperabilidad.proamazonia.dto.DestinoExportacionGpDto;
import ec.gob.mag.interoperabilidad.proamazonia.dto.DestinoIndustriaForestalGpDto;
import ec.gob.mag.interoperabilidad.proamazonia.dto.DetalleGuiaPrimariaDto;
import ec.gob.mag.interoperabilidad.soap_service.CabeceraGuiaPrimaria;
import ec.gob.mag.interoperabilidad.soap_service.DestinoClienteFinalGp;
import ec.gob.mag.interoperabilidad.soap_service.DestinoExportacionGp;
import ec.gob.mag.interoperabilidad.soap_service.DestinoIndustriaForestalGp;
import ec.gob.mag.interoperabilidad.soap_service.DetalleGuiaPrimaria;
import ec.gob.mag.interoperabilidad.soap_service.GetCabeceraGuiaPrimariaResponse;

@Endpoint
public class CabeceraGuiaPrimariaEndpoint {

	private static final String NAMESPACE_URI = "http://mag.gob.ec/interoperabilidad/soap-service";

	@SuppressWarnings({ "rawtypes", "unchecked" })
	@PayloadRoot(namespace = NAMESPACE_URI, localPart = "getCabeceraGuiaPrimariaRequest")
	@ResponsePayload
	public GetCabeceraGuiaPrimariaResponse getCabeceraGuiaPrimaria() {

		// request url
		String url = "http://localhost:8080/micro_interoperabilidad-proamazonia/cabeceraGuiaPrimaria/findAll";
		// create an instance of RestTemplate
		RestTemplate restTemplate = new RestTemplate();
		// create headers
		HttpHeaders headers = new HttpHeaders();
		headers.setContentType(MediaType.APPLICATION_JSON);
		// headers.setAccept(Collections.singletonList(MediaType.APPLICATION_JSON));
		headers.set("Authorization", "Bearer "
				+ "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGxpSWQiOjgxLCJ1c2VyX25hbWUiOiIxNzA3NzIxMTUzIiwic2NvcGUiOlsic2VjcmV0Il0sInJvbGVzIjpbeyJpZFJvbCI6MzIsIm5vbWJyZVJvbCI6IlJPTF9URUNOSUNPX0ZBQ0lMSVRBRE9SX0RFX0NBTVBPIiwicGVybWlzb3MiOlsiYXppLmluZ3Jlc29QZXJmaWwiLCJhbGZyZXNjby5kb3dubG9hZFBsYW5pZmljYWNpb24iLCJhemkudGZjLmxpc3RhUGxhbmlmaWNhY2lvbmVzIiwiYXppLnRmYy5saXN0YVViaWNhY2lvbmVzIiwiYXppLnRmYy5saXN0YUFjdGl2aWRhZGVzIiwiYXppLnRmYy5saXN0YVByb2R1Y3RvcmVzT3JnYW5pemFjaW9uIiwiYXppLnRmYy5saXN0YVByZWRpb3NPcmdhbml6YWNpb24iLCJhemkudGZjLmxpc3RhUHJlZGlvcyIsImF6aS50ZmMubGlzdGFQcmVkaW9zUHJvZHVjdG9yIiwiYXppLnRmYy5lamVjdWNpb24ubGlzdGFBY3RpdmlkYWRlcyIsImF6aS50ZmMuZWplY3VjaW9uLmFjdGl2aWRhZCIsImF6aS50ZmMuZWplY3VjaW9uLmhvamFDYW1wb1BkZiIsImF6aS50ZmMuZWplY3VjaW9uLlBkZi5ob2phQ2FtcG8iLCJhemkudGZjLmVqZWN1Y2lvbi5tdWVzdHJhUGRmIiwiYXppLnRmYy5ndWFyZGFyQWN0aXZpZGFkIiwiYXppLnRmYy5lbGltaW5hckFjdGl2aWRhZCIsImF6aS50ZmMuZWRpdGFyQWN0aXZpZGFkIiwiYXppLnRmYy5wcm9jZXNhckFjdGl2aWRhZCIsImF6aS50ZmMucmVwb3J0ZXMucmVwb3J0ZUFjdGl2aWRhZGVzUERGIiwiYXppLnRmYy5ndWFyZGFyQWN0aXZpZGFkQWRtIiwiYXppLnRmYy5lbGltaW5hckFjdGl2aWRhZEFkbSIsImF6aS50ZmMuZWRpdGFyQWN0aXZpZGFkQWRtIiwiYXppLnRmYy5lamVjdWNpb24ucmVwb3J0ZSIsImF6aS50ZmMuZWplY3VjaW9uLnJlcG9ydGVQZGYiLCJhemkudGZjLnJlcG9ydGVzVEZDIiwiYXppLnRmYy5hcmNoaXZhclBsYW5pZmljYWNpb24iLCJhemkudGZjLmVqZWN1Y2lvbi5TdG9yZUhvamFDYW1wbyIsImF6aS50ZmMuZWplY3VjaW9uLlN0b3JlTXVlc3RyYSIsImF6aS50ZmMuZWplY3VjaW9uLmFzaXN0ZW5jaWEiLCJhemkudGZjLmVqZWN1Y2lvbi5tdWVzdHJhcyIsImF6aS50ZmMuZWplY3VjaW9uLm11ZXN0cmEiLCJhemkudGZjLmVqZWN1Y2lvbi5maW5hbGl6YXJBY3RpdmlkYWQiLCJhemkudGZjLmVqZWN1Y2lvbi5lbGltaW5hckRvY3VtZW50b3NBbGZyZXNjbyIsImF6aS50ZmMuZWplY3VjaW9uLnZpc3VhbGl6YXJEb2N1bWVudG9zQWxmcmVzY28iLCJhemkudGZjLmVqZWN1Y2lvbi52aXN1YWxpemFyQ29udHJhdG9zQWxmcmVzY28iLCJhemkudGZjLmVqZWN1Y2lvbi5zdWJpckhvamFDYW1wbyIsImF6aS50ZmMuZWplY3VjaW9uLnN1YmlyTXVlc3RyYSIsImF6aS50ZmMuZWplY3VjaW9uLnN1YmlyVmFyaW9zIiwiYXppLnRmYy5hcHAubW92aWwiLCJhemkubWFudWFsIiwiYXppLnRmYy5udWV2YVBsYW5pZmljYWNpb25TZW1hbmFsIl19XSwicmVjdXJzb3MiOlt7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLmluZ3Jlc29QZXJmaWwifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYWxmcmVzY28uZG93bmxvYWRQbGFuaWZpY2FjaW9uIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5saXN0YVBsYW5pZmljYWNpb25lcyJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMubGlzdGFVYmljYWNpb25lcyJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMubGlzdGFBY3RpdmlkYWRlcyJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMubGlzdGFQcm9kdWN0b3Jlc09yZ2FuaXphY2lvbiJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMubGlzdGFQcmVkaW9zT3JnYW5pemFjaW9uIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5saXN0YVByZWRpb3MifSx7Im1ldG9kbyI6IkdFVCIsInBhdGgiOiJhemkudGZjLmxpc3RhUHJlZGlvc1Byb2R1Y3RvciJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMuZWplY3VjaW9uLmxpc3RhQWN0aXZpZGFkZXMifSx7Im1ldG9kbyI6IkdFVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi5hY3RpdmlkYWQifSx7Im1ldG9kbyI6IkdFVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi5ob2phQ2FtcG9QZGYifSx7Im1ldG9kbyI6IkdFVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi5QZGYuaG9qYUNhbXBvIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24ubXVlc3RyYVBkZiJ9LHsibWV0b2RvIjoiUE9TVCIsInBhdGgiOiJhemkudGZjLmd1YXJkYXJBY3RpdmlkYWQifSx7Im1ldG9kbyI6IkRFTEVURSIsInBhdGgiOiJhemkudGZjLmVsaW1pbmFyQWN0aXZpZGFkIn0seyJtZXRvZG8iOiJQVVQiLCJwYXRoIjoiYXppLnRmYy5lZGl0YXJBY3RpdmlkYWQifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLnRmYy5wcm9jZXNhckFjdGl2aWRhZCJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMucmVwb3J0ZXMucmVwb3J0ZUFjdGl2aWRhZGVzUERGIn0seyJtZXRvZG8iOiJQT1NUIiwicGF0aCI6ImF6aS50ZmMuZ3VhcmRhckFjdGl2aWRhZEFkbSJ9LHsibWV0b2RvIjoiREVMRVRFIiwicGF0aCI6ImF6aS50ZmMuZWxpbWluYXJBY3RpdmlkYWRBZG0ifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLnRmYy5lZGl0YXJBY3RpdmlkYWRBZG0ifSx7Im1ldG9kbyI6IkdFVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi5yZXBvcnRlIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24ucmVwb3J0ZVBkZiJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMucmVwb3J0ZXNURkMifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLnRmYy5hcmNoaXZhclBsYW5pZmljYWNpb24ifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24uU3RvcmVIb2phQ2FtcG8ifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24uU3RvcmVNdWVzdHJhIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24uYXNpc3RlbmNpYSJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMuZWplY3VjaW9uLm11ZXN0cmFzIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24ubXVlc3RyYSJ9LHsibWV0b2RvIjoiUE9TVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi5maW5hbGl6YXJBY3RpdmlkYWQifSx7Im1ldG9kbyI6IlBPU1QiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24uZWxpbWluYXJEb2N1bWVudG9zQWxmcmVzY28ifSx7Im1ldG9kbyI6IkdFVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi52aXN1YWxpemFyRG9jdW1lbnRvc0FsZnJlc2NvIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLnRmYy5lamVjdWNpb24udmlzdWFsaXphckNvbnRyYXRvc0FsZnJlc2NvIn0seyJtZXRvZG8iOiJQT1NUIiwicGF0aCI6ImF6aS50ZmMuZWplY3VjaW9uLnN1YmlySG9qYUNhbXBvIn0seyJtZXRvZG8iOiJQT1NUIiwicGF0aCI6ImF6aS50ZmMuZWplY3VjaW9uLnN1YmlyTXVlc3RyYSJ9LHsibWV0b2RvIjoiUE9TVCIsInBhdGgiOiJhemkudGZjLmVqZWN1Y2lvbi5zdWJpclZhcmlvcyJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMuYXBwLm1vdmlsIn0seyJtZXRvZG8iOiJHRVQiLCJwYXRoIjoiYXppLm1hbnVhbCJ9LHsibWV0b2RvIjoiR0VUIiwicGF0aCI6ImF6aS50ZmMubnVldmFQbGFuaWZpY2FjaW9uU2VtYW5hbCJ9XSwiZXhwIjoxNjAwOTk0MzM2LCJ1c3VhcmlvcyI6W3sidXN1SWQiOjIsInVzdXBJZCI6MSwicGVyZmlsVGlwbyI6W3sidHBlZk5vbWJyZSI6IlRlY25pY28gRmFjaWxpdGFkb3IgZGUgQ2FtcG8ifSx7InRwZWZOb21icmUiOiJVc3VhcmlvIEJpYmxpb3RlY2EifSx7InRwZWZOb21icmUiOiJSb2wgRnVuY2lvbmFyaW8ifSx7InRwZWZOb21icmUiOiJURkMifV19XSwiYXV0aG9yaXRpZXMiOlsiUk9MX1RFQ05JQ09fRkFDSUxJVEFET1JfREVfQ0FNUE8iXSwianRpIjoiMDBiMzM5YjAtMzA2Yi00MDVmLWE4ZjItODM1YzY3NDkxM2U2IiwicGVyX2lkIjozNzkyODIsImNsaWVudF9pZCI6InVzcl9heml0ZmMifQ.kht9YxJvaZcalDnIzgaX0IzPSC_oobNp7EmQs6LKTdnEhgI5ZN-xwce1R2nlDBNop39lDjC6y3KVjlYbDrxFv8sQi4c0TlW-l_USIV-m4nNFkKDI0R06gRkOCNh3VSJRFY6mYxWbCePDnQWmi0MmRxRqibB5qqcHd1zE7eRJdCTMEg5qhkFD3yqQO3HeL14iHeRHvDehkj7p91DSE67UU22n6eAoSXBlEWyBW3Fwu_AoTRP0COEID74ET81l8UE1PW7RP9EZiHGbmTismF9l2xr4TitkwIKHF2SJCeDgf65xDeMlDZXpV6iPSitNmbpX6szapdzttQa-u_lAyWdmIw");
		// build the request
		HttpEntity request = new HttpEntity(headers);
		// make an HTTP GET request with headers
		ResponseEntity<CabeceraGuiaPrimariaDto[]> response = restTemplate.exchange(url, HttpMethod.GET, request,
				CabeceraGuiaPrimariaDto[].class);
		// check response
		CabeceraGuiaPrimariaDto[] cabeceraGuiaPrimariaDtos = null;
		if (response.getStatusCode() == HttpStatus.OK) {
			System.out.println("Request Successful.");
			cabeceraGuiaPrimariaDtos = response.getBody();
		} else {
			System.out.println("Request Failed");
			System.out.println(response.getStatusCode());
		}

		GetCabeceraGuiaPrimariaResponse cabeceraGuiaPrimariaResponse = new GetCabeceraGuiaPrimariaResponse();
		
		ModelMapper modelMapper = new ModelMapper();
		for (CabeceraGuiaPrimariaDto cabeceraGuia : cabeceraGuiaPrimariaDtos) {
		//	System.out.println("info: " + cabeceraGuia);
			CabeceraGuiaPrimaria cabeceraGuiaPrimariaSoap = modelMapper.map(cabeceraGuia, CabeceraGuiaPrimaria.class);
			if (cabeceraGuia.getDestinoClienteFinalGpDtos() != null) {
				for (DestinoClienteFinalGpDto destino : cabeceraGuia.getDestinoClienteFinalGpDtos()) {
					DestinoClienteFinalGp destinoClienteFinalGpSoap = modelMapper.map(destino,
							DestinoClienteFinalGp.class);
					cabeceraGuiaPrimariaSoap.getDestinoClienteFinalGp().add(destinoClienteFinalGpSoap);
				}
			}
			if (cabeceraGuia.getDestinoExportacionGpDtos() != null) {
				for (DestinoExportacionGpDto destino : cabeceraGuia.getDestinoExportacionGpDtos()) {
					DestinoExportacionGp destinoExportacionGpSoap = modelMapper.map(destino,
							DestinoExportacionGp.class);
					cabeceraGuiaPrimariaSoap.getDestinoExportacionGp().add(destinoExportacionGpSoap);
				}
			}
			if (cabeceraGuia.getDestinoIndustriaForestalGpDtos() != null) {
				for (DestinoIndustriaForestalGpDto destino : cabeceraGuia.getDestinoIndustriaForestalGpDtos()) {
					DestinoIndustriaForestalGp destinoIndustriaForestalGpSoap = modelMapper.map(destino,
							DestinoIndustriaForestalGp.class);
					cabeceraGuiaPrimariaSoap.getDestinoIndustriaForestalGp().add(destinoIndustriaForestalGpSoap);
				}
			}

			if (cabeceraGuia.getDetalleGuiaPrimariaDtos() != null) {
				for (DetalleGuiaPrimariaDto destino : cabeceraGuia.getDetalleGuiaPrimariaDtos()) {
					DetalleGuiaPrimaria detalleGuiaPrimariaSoap = modelMapper.map(destino, DetalleGuiaPrimaria.class);
					cabeceraGuiaPrimariaSoap.getDetalleGuiaPrimaria().add(detalleGuiaPrimariaSoap);
				}
			}

			cabeceraGuiaPrimariaResponse.getCabeceraGuiaPrimaria().add(cabeceraGuiaPrimariaSoap);

		}

		return cabeceraGuiaPrimariaResponse;
	}
}
