//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 03:22:21 PM ECT 
//


package ec.gob.mag.interoperabilidad.soap_service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cabeceraGuiaPrimaria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cabeceraGuiaPrimaria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gmvCodigo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gmvId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="prgId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gmvFechaInicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gmvTipoDestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="licSecuencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prgCodigo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="propietarioRazzonsocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ejecutorNombres" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ejecutorRazonsocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ejecutorRuc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="predioProvincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="predioCanton" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="predioParroquia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="predioSitio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehiculoPlaca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehiculoColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehiculoMarca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="vehiculoTipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guipriFechainicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guipriDuracionhoras" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="guiapriFechafin" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sucIdDestino" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="destinoClienteFinalGp" type="{http://mag.gob.ec/interoperabilidad/soap-service}destinoClienteFinalGp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="destinoExportacionGp" type="{http://mag.gob.ec/interoperabilidad/soap-service}destinoExportacionGp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="destinoIndustriaForestalGp" type="{http://mag.gob.ec/interoperabilidad/soap-service}destinoIndustriaForestalGp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="detalleGuiaPrimaria" type="{http://mag.gob.ec/interoperabilidad/soap-service}detalleGuiaPrimaria" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cabeceraGuiaPrimaria", propOrder = {
    "gmvCodigo",
    "gmvId",
    "prgId",
    "gmvFechaInicio",
    "gmvTipoDestino",
    "licSecuencia",
    "prgCodigo",
    "propietarioRazzonsocial",
    "ejecutorNombres",
    "ejecutorRazonsocial",
    "ejecutorRuc",
    "predioProvincia",
    "predioCanton",
    "predioParroquia",
    "predioSitio",
    "vehiculoPlaca",
    "vehiculoColor",
    "vehiculoMarca",
    "vehiculoTipo",
    "guipriFechainicio",
    "guipriDuracionhoras",
    "guiapriFechafin",
    "sucIdDestino",
    "destinoClienteFinalGp",
    "destinoExportacionGp",
    "destinoIndustriaForestalGp",
    "detalleGuiaPrimaria"
})
public class CabeceraGuiaPrimaria {

    @XmlElement(required = true)
    protected String gmvCodigo;
    protected int gmvId;
    @XmlElement(required = true)
    protected String prgId;
    @XmlElement(required = true)
    protected String gmvFechaInicio;
    @XmlElement(required = true)
    protected String gmvTipoDestino;
    @XmlElement(required = true)
    protected String licSecuencia;
    @XmlElement(required = true)
    protected String prgCodigo;
    @XmlElement(required = true)
    protected String propietarioRazzonsocial;
    @XmlElement(required = true)
    protected String ejecutorNombres;
    @XmlElement(required = true)
    protected String ejecutorRazonsocial;
    @XmlElement(required = true)
    protected String ejecutorRuc;
    @XmlElement(required = true)
    protected String predioProvincia;
    @XmlElement(required = true)
    protected String predioCanton;
    @XmlElement(required = true)
    protected String predioParroquia;
    @XmlElement(required = true)
    protected String predioSitio;
    @XmlElement(required = true)
    protected String vehiculoPlaca;
    @XmlElement(required = true)
    protected String vehiculoColor;
    @XmlElement(required = true)
    protected String vehiculoMarca;
    @XmlElement(required = true)
    protected String vehiculoTipo;
    @XmlElement(required = true)
    protected String guipriFechainicio;
    @XmlElement(required = true)
    protected String guipriDuracionhoras;
    @XmlElement(required = true)
    protected String guiapriFechafin;
    @XmlElement(required = true)
    protected String sucIdDestino;
    @XmlElement(nillable = true)
    protected List<DestinoClienteFinalGp> destinoClienteFinalGp;
    @XmlElement(nillable = true)
    protected List<DestinoExportacionGp> destinoExportacionGp;
    @XmlElement(nillable = true)
    protected List<DestinoIndustriaForestalGp> destinoIndustriaForestalGp;
    @XmlElement(nillable = true)
    protected List<DetalleGuiaPrimaria> detalleGuiaPrimaria;

    /**
     * Gets the value of the gmvCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvCodigo() {
        return gmvCodigo;
    }

    /**
     * Sets the value of the gmvCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvCodigo(String value) {
        this.gmvCodigo = value;
    }

    /**
     * Gets the value of the gmvId property.
     * 
     */
    public int getGmvId() {
        return gmvId;
    }

    /**
     * Sets the value of the gmvId property.
     * 
     */
    public void setGmvId(int value) {
        this.gmvId = value;
    }

    /**
     * Gets the value of the prgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrgId() {
        return prgId;
    }

    /**
     * Sets the value of the prgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrgId(String value) {
        this.prgId = value;
    }

    /**
     * Gets the value of the gmvFechaInicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvFechaInicio() {
        return gmvFechaInicio;
    }

    /**
     * Sets the value of the gmvFechaInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvFechaInicio(String value) {
        this.gmvFechaInicio = value;
    }

    /**
     * Gets the value of the gmvTipoDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvTipoDestino() {
        return gmvTipoDestino;
    }

    /**
     * Sets the value of the gmvTipoDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvTipoDestino(String value) {
        this.gmvTipoDestino = value;
    }

    /**
     * Gets the value of the licSecuencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicSecuencia() {
        return licSecuencia;
    }

    /**
     * Sets the value of the licSecuencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicSecuencia(String value) {
        this.licSecuencia = value;
    }

    /**
     * Gets the value of the prgCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrgCodigo() {
        return prgCodigo;
    }

    /**
     * Sets the value of the prgCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrgCodigo(String value) {
        this.prgCodigo = value;
    }

    /**
     * Gets the value of the propietarioRazzonsocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropietarioRazzonsocial() {
        return propietarioRazzonsocial;
    }

    /**
     * Sets the value of the propietarioRazzonsocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropietarioRazzonsocial(String value) {
        this.propietarioRazzonsocial = value;
    }

    /**
     * Gets the value of the ejecutorNombres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjecutorNombres() {
        return ejecutorNombres;
    }

    /**
     * Sets the value of the ejecutorNombres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjecutorNombres(String value) {
        this.ejecutorNombres = value;
    }

    /**
     * Gets the value of the ejecutorRazonsocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjecutorRazonsocial() {
        return ejecutorRazonsocial;
    }

    /**
     * Sets the value of the ejecutorRazonsocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjecutorRazonsocial(String value) {
        this.ejecutorRazonsocial = value;
    }

    /**
     * Gets the value of the ejecutorRuc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEjecutorRuc() {
        return ejecutorRuc;
    }

    /**
     * Sets the value of the ejecutorRuc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEjecutorRuc(String value) {
        this.ejecutorRuc = value;
    }

    /**
     * Gets the value of the predioProvincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredioProvincia() {
        return predioProvincia;
    }

    /**
     * Sets the value of the predioProvincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredioProvincia(String value) {
        this.predioProvincia = value;
    }

    /**
     * Gets the value of the predioCanton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredioCanton() {
        return predioCanton;
    }

    /**
     * Sets the value of the predioCanton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredioCanton(String value) {
        this.predioCanton = value;
    }

    /**
     * Gets the value of the predioParroquia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredioParroquia() {
        return predioParroquia;
    }

    /**
     * Sets the value of the predioParroquia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredioParroquia(String value) {
        this.predioParroquia = value;
    }

    /**
     * Gets the value of the predioSitio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPredioSitio() {
        return predioSitio;
    }

    /**
     * Sets the value of the predioSitio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPredioSitio(String value) {
        this.predioSitio = value;
    }

    /**
     * Gets the value of the vehiculoPlaca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehiculoPlaca() {
        return vehiculoPlaca;
    }

    /**
     * Sets the value of the vehiculoPlaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiculoPlaca(String value) {
        this.vehiculoPlaca = value;
    }

    /**
     * Gets the value of the vehiculoColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehiculoColor() {
        return vehiculoColor;
    }

    /**
     * Sets the value of the vehiculoColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiculoColor(String value) {
        this.vehiculoColor = value;
    }

    /**
     * Gets the value of the vehiculoMarca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehiculoMarca() {
        return vehiculoMarca;
    }

    /**
     * Sets the value of the vehiculoMarca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiculoMarca(String value) {
        this.vehiculoMarca = value;
    }

    /**
     * Gets the value of the vehiculoTipo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehiculoTipo() {
        return vehiculoTipo;
    }

    /**
     * Sets the value of the vehiculoTipo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiculoTipo(String value) {
        this.vehiculoTipo = value;
    }

    /**
     * Gets the value of the guipriFechainicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuipriFechainicio() {
        return guipriFechainicio;
    }

    /**
     * Sets the value of the guipriFechainicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuipriFechainicio(String value) {
        this.guipriFechainicio = value;
    }

    /**
     * Gets the value of the guipriDuracionhoras property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuipriDuracionhoras() {
        return guipriDuracionhoras;
    }

    /**
     * Sets the value of the guipriDuracionhoras property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuipriDuracionhoras(String value) {
        this.guipriDuracionhoras = value;
    }

    /**
     * Gets the value of the guiapriFechafin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuiapriFechafin() {
        return guiapriFechafin;
    }

    /**
     * Sets the value of the guiapriFechafin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuiapriFechafin(String value) {
        this.guiapriFechafin = value;
    }

    /**
     * Gets the value of the sucIdDestino property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSucIdDestino() {
        return sucIdDestino;
    }

    /**
     * Sets the value of the sucIdDestino property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSucIdDestino(String value) {
        this.sucIdDestino = value;
    }

    /**
     * Gets the value of the destinoClienteFinalGp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinoClienteFinalGp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinoClienteFinalGp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DestinoClienteFinalGp }
     * 
     * 
     */
    public List<DestinoClienteFinalGp> getDestinoClienteFinalGp() {
        if (destinoClienteFinalGp == null) {
            destinoClienteFinalGp = new ArrayList<DestinoClienteFinalGp>();
        }
        return this.destinoClienteFinalGp;
    }

    /**
     * Gets the value of the destinoExportacionGp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinoExportacionGp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinoExportacionGp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DestinoExportacionGp }
     * 
     * 
     */
    public List<DestinoExportacionGp> getDestinoExportacionGp() {
        if (destinoExportacionGp == null) {
            destinoExportacionGp = new ArrayList<DestinoExportacionGp>();
        }
        return this.destinoExportacionGp;
    }

    /**
     * Gets the value of the destinoIndustriaForestalGp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinoIndustriaForestalGp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinoIndustriaForestalGp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DestinoIndustriaForestalGp }
     * 
     * 
     */
    public List<DestinoIndustriaForestalGp> getDestinoIndustriaForestalGp() {
        if (destinoIndustriaForestalGp == null) {
            destinoIndustriaForestalGp = new ArrayList<DestinoIndustriaForestalGp>();
        }
        return this.destinoIndustriaForestalGp;
    }

    /**
     * Gets the value of the detalleGuiaPrimaria property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalleGuiaPrimaria property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalleGuiaPrimaria().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetalleGuiaPrimaria }
     * 
     * 
     */
    public List<DetalleGuiaPrimaria> getDetalleGuiaPrimaria() {
        if (detalleGuiaPrimaria == null) {
            detalleGuiaPrimaria = new ArrayList<DetalleGuiaPrimaria>();
        }
        return this.detalleGuiaPrimaria;
    }

}
