//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 03:22:21 PM ECT 
//


package ec.gob.mag.interoperabilidad.soap_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for destinoClienteFinalGp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="destinoClienteFinalGp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gmvCodigo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prgId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gmvFechaInicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="idCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cedulaCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="razonsocial" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clfNumeroEstablecimiento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="direccionCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="telefCliente" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "destinoClienteFinalGp", propOrder = {
    "gmvCodigo",
    "prgId",
    "gmvFechaInicio",
    "idCliente",
    "cedulaCliente",
    "razonsocial",
    "clfNumeroEstablecimiento",
    "direccionCliente",
    "telefCliente",
    "provincia",
    "canton",
    "parroquia",
    "id"
})
public class DestinoClienteFinalGp {

    @XmlElement(required = true)
    protected String gmvCodigo;
    protected int prgId;
    @XmlElement(required = true)
    protected String gmvFechaInicio;
    @XmlElement(required = true)
    protected String idCliente;
    @XmlElement(required = true)
    protected String cedulaCliente;
    @XmlElement(required = true)
    protected String razonsocial;
    @XmlElement(required = true)
    protected String clfNumeroEstablecimiento;
    @XmlElement(required = true)
    protected String direccionCliente;
    @XmlElement(required = true)
    protected String telefCliente;
    @XmlElement(required = true)
    protected String provincia;
    @XmlElement(required = true)
    protected String canton;
    @XmlElement(required = true)
    protected String parroquia;
    @XmlElement(required = true)
    protected String id;

    /**
     * Gets the value of the gmvCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvCodigo() {
        return gmvCodigo;
    }

    /**
     * Sets the value of the gmvCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvCodigo(String value) {
        this.gmvCodigo = value;
    }

    /**
     * Gets the value of the prgId property.
     * 
     */
    public int getPrgId() {
        return prgId;
    }

    /**
     * Sets the value of the prgId property.
     * 
     */
    public void setPrgId(int value) {
        this.prgId = value;
    }

    /**
     * Gets the value of the gmvFechaInicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvFechaInicio() {
        return gmvFechaInicio;
    }

    /**
     * Sets the value of the gmvFechaInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvFechaInicio(String value) {
        this.gmvFechaInicio = value;
    }

    /**
     * Gets the value of the idCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdCliente() {
        return idCliente;
    }

    /**
     * Sets the value of the idCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdCliente(String value) {
        this.idCliente = value;
    }

    /**
     * Gets the value of the cedulaCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCedulaCliente() {
        return cedulaCliente;
    }

    /**
     * Sets the value of the cedulaCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCedulaCliente(String value) {
        this.cedulaCliente = value;
    }

    /**
     * Gets the value of the razonsocial property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRazonsocial() {
        return razonsocial;
    }

    /**
     * Sets the value of the razonsocial property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRazonsocial(String value) {
        this.razonsocial = value;
    }

    /**
     * Gets the value of the clfNumeroEstablecimiento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClfNumeroEstablecimiento() {
        return clfNumeroEstablecimiento;
    }

    /**
     * Sets the value of the clfNumeroEstablecimiento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClfNumeroEstablecimiento(String value) {
        this.clfNumeroEstablecimiento = value;
    }

    /**
     * Gets the value of the direccionCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionCliente() {
        return direccionCliente;
    }

    /**
     * Sets the value of the direccionCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionCliente(String value) {
        this.direccionCliente = value;
    }

    /**
     * Gets the value of the telefCliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefCliente() {
        return telefCliente;
    }

    /**
     * Sets the value of the telefCliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefCliente(String value) {
        this.telefCliente = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvincia(String value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the canton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanton() {
        return canton;
    }

    /**
     * Sets the value of the canton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanton(String value) {
        this.canton = value;
    }

    /**
     * Gets the value of the parroquia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParroquia() {
        return parroquia;
    }

    /**
     * Sets the value of the parroquia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParroquia(String value) {
        this.parroquia = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
