//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 03:22:21 PM ECT 
//


package ec.gob.mag.interoperabilidad.soap_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for destinoIndustriaForestalGp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="destinoIndustriaForestalGp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gmvCodigo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="prgId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="gmvFechaInicio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="direccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="conTelefo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="provincia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="canton" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parroquia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "destinoIndustriaForestalGp", propOrder = {
    "gmvCodigo",
    "prgId",
    "gmvFechaInicio",
    "direccion",
    "conTelefo",
    "provincia",
    "canton",
    "parroquia",
    "id"
})
public class DestinoIndustriaForestalGp {

    @XmlElement(required = true)
    protected String gmvCodigo;
    protected int prgId;
    @XmlElement(required = true)
    protected String gmvFechaInicio;
    @XmlElement(required = true)
    protected String direccion;
    @XmlElement(required = true)
    protected String conTelefo;
    @XmlElement(required = true)
    protected String provincia;
    @XmlElement(required = true)
    protected String canton;
    @XmlElement(required = true)
    protected String parroquia;
    @XmlElement(required = true)
    protected String id;

    /**
     * Gets the value of the gmvCodigo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvCodigo() {
        return gmvCodigo;
    }

    /**
     * Sets the value of the gmvCodigo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvCodigo(String value) {
        this.gmvCodigo = value;
    }

    /**
     * Gets the value of the prgId property.
     * 
     */
    public int getPrgId() {
        return prgId;
    }

    /**
     * Sets the value of the prgId property.
     * 
     */
    public void setPrgId(int value) {
        this.prgId = value;
    }

    /**
     * Gets the value of the gmvFechaInicio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmvFechaInicio() {
        return gmvFechaInicio;
    }

    /**
     * Sets the value of the gmvFechaInicio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmvFechaInicio(String value) {
        this.gmvFechaInicio = value;
    }

    /**
     * Gets the value of the direccion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * Sets the value of the direccion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccion(String value) {
        this.direccion = value;
    }

    /**
     * Gets the value of the conTelefo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConTelefo() {
        return conTelefo;
    }

    /**
     * Sets the value of the conTelefo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConTelefo(String value) {
        this.conTelefo = value;
    }

    /**
     * Gets the value of the provincia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProvincia() {
        return provincia;
    }

    /**
     * Sets the value of the provincia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProvincia(String value) {
        this.provincia = value;
    }

    /**
     * Gets the value of the canton property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanton() {
        return canton;
    }

    /**
     * Sets the value of the canton property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanton(String value) {
        this.canton = value;
    }

    /**
     * Gets the value of the parroquia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParroquia() {
        return parroquia;
    }

    /**
     * Sets the value of the parroquia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParroquia(String value) {
        this.parroquia = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
