//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 03:22:21 PM ECT 
//


package ec.gob.mag.interoperabilidad.soap_service;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for detalleGuiaPrimaria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="detalleGuiaPrimaria">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="licId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="espId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="especie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="espNombre" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesTipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tipoEspecie" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="espTipo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesLargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesAncho" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesEspesor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesUnidades" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesVolumen" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesVolumenMovilizado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gesVolumenMovilizado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "detalleGuiaPrimaria", propOrder = {
    "content"
})
public class DetalleGuiaPrimaria {

    @XmlElementRefs({
        @XmlElementRef(name = "gesUnidades", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gesVolumen", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gesAncho", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gesEspesor", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tipoEspecie", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gesVolumenMovilizado", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "especie", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "licId", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "espId", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gesLargo", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "gesTipo", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "espTipo", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "espNombre", namespace = "http://mag.gob.ec/interoperabilidad/soap-service", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> content;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "GesVolumenMovilizado" is used by two different parts of a schema. See: 
     * line 109 of file:/Users/ezamora/Documents/Personal/Consultorias/MAGAP/MAAE-%20ProAmazonía%20/ws_git_interOpe/maaeproamazoniaspf/api_interoperabilidad-soap/src/main/resources/cabeceraGuiaPrimaria.xsd
     * line 108 of file:/Users/ezamora/Documents/Personal/Consultorias/MAGAP/MAAE-%20ProAmazonía%20/ws_git_interOpe/maaeproamazoniaspf/api_interoperabilidad-soap/src/main/resources/cabeceraGuiaPrimaria.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getContent() {
        if (content == null) {
            content = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.content;
    }

}
