//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.24 at 03:22:21 PM ECT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://mag.gob.ec/interoperabilidad/soap-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ec.gob.mag.interoperabilidad.soap_service;
